[package]
name = "rusted-puzzles"
version = "0.1.0"
edition = "2024"

[dependencies]
fun_time = "0.3.4"
#lazy_static = "1.5.0"
#regex = "1.12.2"
#futures = "0.3.31"
#tokio = { version = "1.49.0", features = ["full"] }